name: sonipresence
description: |
  Client-server application for compact mobile devices, primarily for Android devices. 
  The main purpose of the application is to record the voice environment by the server side and transfer
  the audio file with geolocation and time stamp to the client side to ensure the guardian is aware of the safety, 
  location and environment of the ward.
publish_to: none   # Don't publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^15.1.2
  flutter_blue_plus: ^1.35.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

